[bell]
duration = 0

[cursor.style]
blinking = "Off"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
builtin_box_drawing = true
size = 12

[font.normal]
family = "Monaco Nerd Font Mono"
style = "Regular"

[[keyboard.bindings]]
chars = "@"
key = 19
mods = "Alt"

[[keyboard.bindings]]
chars = "{"
key = 26
mods = "Alt"

[[keyboard.bindings]]
chars = "["
key = 28
mods = "Alt"

[[keyboard.bindings]]
chars = "]"
key = 25
mods = "Alt"

[[keyboard.bindings]]
chars = "}"
key = 29
mods = "Alt"

[[keyboard.bindings]]
chars = '\'
key = 50
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0000"
key = "Space"
mods = "Control"

[scrolling]
history = 10000
multiplier = 3

[terminal.shell]
args = ["-l", "-c", "tmux new -As local"]
program = "/bin/bash"

[window]
opacity = 1

[window.dimensions]
columns = 120
lines = 25

[window.padding]
x = 5
y = 2

[general]
import = [
    "~/.config/alacritty/osx.toml",
    "~/.config/alacritty/themes/gruvbox_dark.toml",
]

[terminal]
