import = ["~/.config/alacritty/themes/gruvbox_dark.toml"]

[bell]
duration = 0

[cursor.style]
blinking = "Off"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
builtin_box_drawing = false
size = 16

[font.normal]
family = "Monaco Nerd Font Mono"
style = "Regular"

[[keyboard.bindings]]
chars = "@"
key = 19
mods = "Alt"

[[keyboard.bindings]]
chars = "{"
key = 26
mods = "Alt"

[[keyboard.bindings]]
chars = "["
key = 28
mods = "Alt"

[[keyboard.bindings]]
chars = "]"
key = 25
mods = "Alt"

[[keyboard.bindings]]
chars = "}"
key = 29
mods = "Alt"

[[keyboard.bindings]]
chars = '\'
key = 50
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0000"
key = "Space"
mods = "Control"

[scrolling]
history = 10000
multiplier = 3

[shell]
args = ["-l", "-c", "tmux new -As local"]
program = "/bin/bash"

[window]
decorations = "none"
opacity = 1
option_as_alt = "None"

[window.dimensions]
columns = 120
lines = 25

[window.padding]
x = 5
y = 2
