#!/usr/bin/env bash


if is_app_installed alacritty; then
  mkdir -p ~/.config/alacritty
  
  if [ "${darwin}" = "true" ]; then
    check_dotfile ~/.config/alacritty/alacritty.yml $(pwd)/alacritty/alacritty-osx.yml 
  else
    check_dotfile ~/.config/alacritty/alacritty.yml $(pwd)/alacritty/alacritty-linux.yml 
  fi
fi
