#!/usr/bin/env bash

# try-lock "git-lock" || return 0
if is_app_installed git; then
  mkdir -p ~/.config/git

  touch ~/.gitconfig
  check_dotfile ~/.config/git/config "$PWD"/git/config 
  check_dotfile ~/.gitignore_global "$PWD"/git/gitignore_global 
  
  export GIT_TEMPLATE_DIR=$PWD/git-templates

  cfg="command git --no-optional-locks config --global"
  $cfg url."git@github.com:".insteadOf "https://github.com/"

  if is_app_installed gpg; then
    export GPG_TTY=$(tty)
    if ! $cfg --get user.signingkey &>/dev/null; then
      GPG_SIGNINGKEY=$(gpg --list-secret-keys --keyid-format LONG | grep sec | awk '{print $2}' | cut -d/ -f 2)

      if [[ -n $GPG_SIGNINGKEY ]]; then 
        $cfg user.signingkey $GPG_SIGNINGKEY
        $cfg commit.gpgsign true
        $cfg gpg.program gpg
      fi
    fi
  fi

  source ./git/git-wrappers

  # install git-filter-repo
  if [ ! -f "$WORKDIR/.git-filter-repo/git-filter-repo" ]; then
    pushd "$WORKDIR" >&1 >/dev/null
    git clone https://github.com/newren/git-filter-repo.git .git-filter-repo  --depth=1 --quiet
    pushd .git-filter-repo >&1 >/dev/null
    git remote set-branches origin docs 
    git fetch --dept=1 --quiet
    mkdir -p man/man1
    git show origin/docs:man1/git-filter-repo.1 >man/man1/git-filter-repo.1
  fi

  pathmunge "$WORKDIR/.git-filter-repo"

  # git prompt
  source "$PWD"/git/git-prompt
fi
