#!/usr/bin/env bash

if is_app_installed git; then
  if is_app_installed gpg; then
    GPG_SIGNINGKEY=$(gpg --list-secret-keys --keyid-format LONG | grep sec | awk '{print $2}' | cut -d/ -f 2)

    cfg="git config --global"

    if [[ -n $GPG_SIGNINGKEY ]]; then 
      export GPG_TTY=$(tty)
      $cfg user.signingkey $GPG_SIGNINGKEY
      $cfg commit.gpgsign true
      $cfg gpg.program gpg
    fi
  fi
  [[ -r ~/.gitignore_global || -L ~/.gitignore_global ]] || ln -s $(pwd)/git/gitignore_global ~/.gitignore_global

  # core config

  $cfg core.excludesfile "~/.gitignore_global"
  $cfg core.autocrlf input
  $cfg core.editor vim

  # aliases

  $cfg alias.lg "log --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --date=relative"
  $cfg alias.st status

  # init

  $cfg init.templatedir $(pwd)/git-templates

  # use new protocol

  $cfg protocol.version 2

  source ./git/git-wrappers
fi
