#!/usr/bin/env bash

# avoid bash history duplicates..
HISTCONTROL=ignoredups:erasedups
HISTSIZE=20000
# When the shell exits, append to the history file instead of overwriting it
shopt -s histappend

# Using \[ and \] around colors is necessary to prevent
# issues with command line editing/browsing/completion!
PROMPT_DIRTRIM=4                           # shorten deep paths in the prompt
line0='\[\033]0;Per Aspera Ad Astra\007\]' # set window title
line1="\[${CYAN}\]\u\[${NC}\]"             # user
line1="$line1@\[${GREEN}\]\h\[${NC}\]"     # host
line1="$line1 "                            # seperator
line1="$line1\[${B_YELLOW}\]\w\[${NC}\]"   # working directory

line2="\n"
# line2="\[${MAGENTA}\]\D{%b %d}\[${NC}\]" # Date, for more info, man 3 strftime
# line2="$line2 "                          # seperator
line2="$line2\[${WHITE}\]\A\[${NC}\]"      # 24h time
line2="$line2 \$ "                         # prompt: always $

_PS1="${line0}__nonzero_return____virtualenv_info__${line1}${line2}"

PROMPT_COMMAND='__set_ps1;__nonzero_return;__virtualenv_info;__bash_history_sync'

function __bash_history_sync() {
  command history -a
  command history -c
  command history -r
}

function __set_ps1() {
  local exit=$?
  PS1=$_PS1
  return $exit
}

function __nonzero_return() {
  local exit=$?
  local prompt_ok="\[${GREEN}\]✔\[${NC}\] "
  local prompt_fail="\[${RED}\]✘-${exit}\[${NC}\] "
  local status_code=$prompt_ok
  [[ $exit -ne 0 ]] && status_code=$prompt_fail
  PS1="${PS1/__nonzero_return__/$status_code}"
  return $exit
}

export VIRTUAL_ENV_DISABLE_PROMPT=1

function __virtualenv_info() {
  local exit=$?
  local str=""
  if [[ -n "$VIRTUAL_ENV" ]]; then
    local venv
    venv=$(basename "$(dirname $VIRTUAL_ENV)")
    str="(\[${BLUE}\]venv:\[${B_BLUE}\]${venv}\[${NC}\]) "
  fi
  PS1="${PS1/__virtualenv_info__/$str}"
  return $exit
}
