#!/usr/bin/env bash

# load misc
INIT_HOME=$HOME/scripts
cd $INIT_HOME
source misc

scripts=(`find . -mindepth 2 -not -path "./.git/*" -perm 755 -type f`)
# debug "${scripts[@]}"

for script in "${scripts[@]}"; do
  if [[ "$script" =~ ^.*/init$ ]]; then
    # debug "${script}"
    source ${script}
    continue
  fi
  path=$(dirname $(realpath "${script}"))
  [[ "$PATH" != *${path}* ]] && PATH=${PATH}:${path}
#  debug "\$PATH:${path}"
  export PATH
done
cd - >&1 >/dev/null
