#!/bin/bash

# load misc
INIT_HOME=$HOME/scripts
cd $INIT_HOME
source misc

scripts=(`find . -not -path "./.git/*" -perm 755 -type f -exec dirname {} \; | sort | uniq`)
#debug "${scripts[@]}"

for script in "${scripts[@]}"; do
  path=$(realpath "${script}")
  PATH=$PATH:${path}
#  debug "\$PATH:$path"
  export PATH
done
cd - >&1 >/dev/null