#!/usr/bin/env bash

# load misc
INIT_HOME=$HOME/scripts
cd $INIT_HOME
source misc

# Source completions
[[ "$(which kubectl)" ]] && source <(kubectl completion bash)
[[ "$(which k3d)" ]] && source <(k3d completion bash)

# install fzf
if [ ! -d "$WORKDIR/.fzf" ]; then
  if is_app_installed git; then
    git clone --quiet --depth 1 https://github.com/junegunn/fzf.git $WORKDIR/.fzf
    $WORKDIR/.fzf/install --completion --key-bindings --no-update-rc
  fi
fi
[ -f ~/.fzf.bash ] && source ~/.fzf.bash

scripts=(`find . -mindepth 2 -not -path "./.git/*" -perm /u+x -type f`)
[[ -n $DEBUG ]] && debug "scripts: ${scripts[@]}"

for script in "${scripts[@]}"; do
  if [[ "$script" =~ ^.*/init$ ]]; then
    [[ -n $DEBUG ]] && debug "loading: ${script}"
    source ${script}
    continue
  fi
  path=$(dirname $(realpath "${script}"))
  if [[ "$PATH" != *${path}* ]]; then
    PATH=${PATH}:${path}
    [[ -n $DEBUG ]] && debug "\$PATH:${path}"
  fi
  export PATH
done
cd - >&1 >/dev/null
