#!/usr/bin/env bash

# make sure WORKDIR exists
[[ -n ${WORKDIR} ]] && mkdir -p "$WORKDIR"

# bash completion user dir
mkdir -p "$BASH_COMPLETION_USER_DIR"/completions

install --preserve-timestamps --mode=644 inputrc ${HOME}/.inputrc
