#!/usr/bin/env bash


if is_app_installed vim; then
  export VISUAL=vim
  export EDITOR="$VISUAL"

  mkdir -p ~/.vim/undodir
  mkdir -p ~/.vim/spell
  mkdir -p ~/.vim/after/ftplugin

  check_dotfile ~/.vimrc || ln -s $(pwd)/vim/vimrc ~/.vimrc
  check_dotfile ~/.vim/after/ftplugin/python.vim || ln -s $(pwd)/vim/after/ftplugin/python.vim ~/.vim/after/ftplugin/python.vim
  check_dotfile ~/.vim/after/ftplugin/yaml.vim || ln -s $(pwd)/vim/after/ftplugin/yaml.vim ~/.vim/after/ftplugin/yaml.vim
  check_dotfile ~/.vim/after/ftplugin/javascript.vim || ln -s $(pwd)/vim/after/ftplugin/javascript.vim ~/.vim/after/ftplugin/javascript.vim
  check_dotfile ~/.vim/after/ftplugin/rust.vim || ln -s $(pwd)/vim/after/ftplugin/rust.vim ~/.vim/after/ftplugin/rust.vim
  check_dotfile ~/.vim/coc-settings.json || ln -s $(pwd)/vim/coc-settings.json ~/.vim/coc-settings.json
  check_dotfile ~/.vim/spell/en.utf-8.add || ln -s $(pwd)/vim/spell/en.utf-8.add ~/.vim/spell/en.utf-8.add
fi
