#!/usr/bin/env bash

if is_app_installed vim; then
  export VISUAL=vim
  export EDITOR="$VISUAL"

  mkdir -p ~/.vim/swapfiles
  mkdir -p ~/.vim/backups

  [[ -r ~/.vimrc || -L ~/.vimrc ]] || ln -s $(pwd)/vim/vimrc ~/.vimrc
fi
