{{- $osname := .chezmoi.os -}}
{{- if eq .chezmoi.os "darwin" -}}
{{-   $osname = "macos" -}}
{{- end -}}
[".local"]
type = "archive"
url = 'https://github.com/neovim/neovim/releases/latest/download/nvim-{{- $osname }}-{{ .uname_arch }}.tar.gz'
stripComponents = 1
refreshPeriod = "672h"  # four weeks
