#:schema https://mise.jdx.dev/schema/mise.json

min_version = "2026.3.9"

[tools]
chezmoi = "latest"
glow = "latest"
jwt = "latest"
lazygit = "latest"
node = "latest"
python = "latest"
rust = "latest"
starship = "latest"
usage = "latest"
uv = "latest"
yazi = "latest"
