#!/usr/bin/env bash

# install fzf
if [ ! -d "$WORKDIR/.fzf" ]; then
  if is_app_installed git; then
    git clone --quiet --depth 1 https://github.com/junegunn/fzf.git $WORKDIR/.fzf
    $WORKDIR/.fzf/install --completion --key-bindings --no-update-rc
  fi
fi

# [ -f ~/.fzf.bash ] && source ~/.fzf.bash

# Setup fzf
# ---------
pathmunge "${WORKDIR}/.fzf/bin"

# Auto-completion
# ---------------
if [[ ! -f $BASH_COMPLETION_USER_DIR/completions/fzf ]]; then
  check_dotfile $BASH_COMPLETION_USER_DIR/completions/fzf $WORKDIR/.fzf/shell/completion.bash 
fi

# Key bindings
# ------------
source "$WORKDIR/.fzf/shell/key-bindings.bash"

source $(pwd)/fzf/config
