#!/usr/bin/env bash

show_available_sessions() {
  if [[ -z "${TMUX}" ]]; then
    sessions=$( tmux ls 2> /dev/null | awk '! /attached/ { sub(":", "", $1); print $1; }' | xargs echo )
    if [[ ! -z $sessions ]]; then
      echo "==> Available tmux sessions: $sessions"
      echo "Connect with: tmux new -As <session name>"
    fi
    unset sessions
  fi
}

tssh() {
  ssh -t $@ "tmux attach || tmux new"
}

if is_app_installed tmux; then
  if ! is_app_installed git; then
    warn "git command not found. Install it first."
  else
    # Add dotfiles to home
    check_dotfile ~/.tmux.conf || ln -s $(pwd)/tmux/tmux.conf ~/.tmux.conf
    # check_dotfile ~/.tmux.default.theme || ln -s $(pwd)/tmux/tmux.default.theme.conf ~/.tmux.default.theme
    # check_dotfile ~/.tmux.gruvbox-dark.theme || ln -s $(pwd)/tmux/tmux.gruvbox-dark.theme.conf ~/.tmux.gruvbox-dark.theme
    check_dotfile ~/.tmux.remote.conf || ln -s $(pwd)/tmux/tmux.remote.conf ~/.tmux.remote.conf

    # Check if tpm is installed
    if [ ! -e "$HOME/.tmux/plugins/tpm" ]; then
      info "Tmux Plugin Manager not found."
      info "Installing now..."
      git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

      # Install TPM Plugins
      info "Installing TPM Plugins"
      TMUX_PLUGIN_MANAGER_PATH=~/.tmux/plugins "$HOME"/.tmux/plugins/tpm/bin/install_plugins
      info "Done"
    fi

    # show available tmux sessions
    # show_available_sessions
  fi
fi
