CompileFlags:
  Remove:
    - -fno-canonical-system-headers
    - -Werror
  Add:
    - -Wall
    - -O2
    - -Wextra
    - -Wshadow
    - -Wconversion
    - -Wfloat-equal
    - -Wno-unused-const-variable
    - -Wno-sign-conversion
    - -ferror-limit=0
Index:
  Background: Skip
Hover:
  ShowAKA: true
---
Diagnostics:
  ClangTidy:
    Add:
      - clang-diagnostic-*
      - clang-analyzer-*
      - cppcoreguidelines-*
      - modernize-*
    Remove:
      - llvm-header-guard
      - modernize-use-trailing-return-type
